name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    runs-on: ${{ github.repository == 'antiwork/helper' && 'ubicloud-standard-2' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3] # 3 parallel jobs

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install

      - name: Build packages
        run: pnpm run-on-packages build

      - name: Run shard ${{ matrix.shard }} of tests
        run: pnpm test -- --shard=${{ matrix.shard }}/3
