name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-packages:
    runs-on: ${{ github.repository == 'antiwork/helper' && 'ubicloud-standard-2' || 'ubuntu-latest' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install

      - name: Run package tests
        run: pnpm run-on-packages test

  test:
    runs-on: ${{ github.repository == 'antiwork/helper' && 'ubicloud-standard-2' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        ci_node_index: [0, 1, 2, 3]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install

      - name: Download previous test timing reports
        uses: dawidd6/action-download-artifact@v3
        with:
          branch: main
          name: vitest-junit-reports
          path: tmp/junit-reports-downloaded
        continue-on-error: true

      - name: Split tests by timings
        uses: r7kamura/split-tests-by-timings@v0
        id: split-tests
        with:
          reports: tmp/junit-reports-downloaded
          glob: 'tests/**/*.test.ts'
          index: ${{ matrix.ci_node_index }}
          total: 4

      - name: Run tests (node ${{ matrix.ci_node_index }})
        run: |
          pnpm vitest run \
            --pool=threads \
            --reporter=junit \
            --reporter=default \
            --outputFile.junit=tmp/junit-reports/junit-${{ matrix.ci_node_index }}.xml \
            ${{ steps.split-tests.outputs.paths }}

      - name: Upload test timing reports
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: vitest-junit-reports
          path: tmp/junit-reports